import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        display: ["Orbitron", "monospace"],
        ui: ["Orbitron", "monospace"],
        mono: ["JetBrains Mono", "Courier New", "monospace"],
        body: ["Source Han Sans", "Noto Sans SC", "Inter", "sans-serif"],
      },
      colors: {
        border: {
          DEFAULT: "hsl(var(--border))",
          strong: "hsl(var(--border-strong))",
          accent: "hsl(var(--border-accent))",
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        ef: {
          black: "hsl(var(--ef-black))",
          "black-soft": "hsl(var(--ef-black-soft))",
          "black-muted": "hsl(var(--ef-black-muted))",
          "dark-gray": "hsl(var(--ef-dark-gray))",
          gray: "hsl(var(--ef-gray))",
          "gray-mid": "hsl(var(--ef-gray-mid))",
          "gray-light": "hsl(var(--ef-gray-light))",
          "white-muted": "hsl(var(--ef-white-muted))",
          "white-soft": "hsl(var(--ef-white-soft))",
          white: "hsl(var(--ef-white))",
          "pure-white": "hsl(var(--ef-pure-white))",
          yellow: "hsl(var(--ef-yellow))",
          "yellow-dark": "hsl(var(--ef-yellow-dark))",
          lime: "hsl(var(--ef-lime))",
          "lime-dark": "hsl(var(--ef-lime-dark))",
          blue: "hsl(var(--ef-blue))",
          "blue-light": "hsl(var(--ef-blue-light))",
          "blue-dark": "hsl(var(--ef-blue-dark))",
          cyan: "hsl(var(--ef-cyan))",
          red: "hsl(var(--ef-red))",
          green: "hsl(var(--ef-green))",
          orange: "hsl(var(--ef-orange))",
          purple: "hsl(var(--ef-purple))",
        },
        surface: {
          canvas: "hsl(var(--surface-canvas))",
          0: "hsl(var(--surface-0))",
          1: "hsl(var(--surface-1))",
          2: "hsl(var(--surface-2))",
          3: "hsl(var(--surface-3))",
          hover: "hsl(var(--surface-hover))",
          active: "hsl(var(--surface-active))",
        },
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
          6: "var(--chart-6)",
          7: "var(--chart-7)",
          8: "var(--chart-8)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        glow: "var(--shadow-glow)",
        "glow-sm": "var(--shadow-glow-sm)",
        "glow-md": "var(--shadow-glow-md)",
        "glow-lg": "var(--shadow-glow-lg)",
        accent: "var(--shadow-accent)",
      },
      zIndex: {
        below: "-1",
        base: "0",
        raised: "1",
        dropdown: "100",
        sticky: "200",
        header: "1000",
        overlay: "1500",
        modal: "2000",
        toast: "3000",
        tooltip: "4000",
        max: "9999",
      },
      opacity: {
        overlay: "var(--opacity-overlay)",
        hover: "var(--opacity-hover)",
        disabled: "var(--opacity-disabled)",
        border: "var(--opacity-border)",
        focus: "var(--opacity-focus)",
        muted: "var(--opacity-muted)",
      },
      transitionDuration: {
        instant: "100ms",
        fast: "150ms",
        normal: "250ms",
        slow: "400ms",
        slower: "800ms",
      },
      transitionTimingFunction: {
        default: "cubic-bezier(0.25, 0.8, 0.25, 1)",
        bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        sharp: "cubic-bezier(0.4, 0, 0.2, 1)",
        smooth: "cubic-bezier(0.45, 0, 0.55, 1)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "dialog-in": {
          from: { opacity: "0", transform: "translate(-50%, -48%) scale(0.96)" },
          to: { opacity: "1", transform: "translate(-50%, -50%) scale(1)" },
        },
        "switch-thumb-spin": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "20%, 60%": { transform: "translateX(-4px)" },
          "40%, 80%": { transform: "translateX(4px)" },
        },
        slideUp: {
          from: { transform: "translateY(100%)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        particleDrift: {
          "0%":   { transform: "translate(0, 0)" },
          "33%":  { transform: "translate(2px, -3px)" },
          "66%":  { transform: "translate(-2px, 2px)" },
          "100%": { transform: "translate(0, 0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
        "accordion-up": "accordion-up 0.2s cubic-bezier(0.7, 0, 1, 1)",
        "dialog-in": "dialog-in 0.3s ease forwards",
        "switch-spin": "switch-thumb-spin 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        shake: "shake 0.4s var(--ease-sharp, cubic-bezier(0.4, 0, 0.2, 1))",
        "slide-up": "slideUp 0.3s var(--ease-sharp, cubic-bezier(0.4, 0, 0.2, 1)) forwards",
        "particle-drift": "particleDrift 3s ease-in-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
